# Site settings
title: NekoboyAI - Open-Sourceï¼†CC-by AI Artist
url: "https://nekoboyai.github.io"

# Build settings
# markdown: redcarpet
markdown: kramdown
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "fenced_code_blocks"]
